fix: handle empty user collection
As per error

2024-05-31T09:27:39.382Z	Caused by:
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex
at java.base/java.util.ArrayList.get(Unknown Source)
at java.base/java.util.Collections$UnmodifiableList.get(Unknown Source)
uk.nhs.tis.trainee.notifications.service.UserAccountService.getUserDetails(UserAccountService.java:170)

and guidance on the hasUsers() method: "For responses, this returns true if the service returned a value for the
Users property. This DOES NOT check that the value is non-empty (for
which, you should check the isEmpty() method on the property)."

NO-TICKET